name: Auto Version Bump and Tag

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  bump-version:
    # Evita que a própria action crie um loop se empurrar pra master (usando [skip ci] no commit tb ajuda, mas é bom proteger)
    if: "!startsWith(github.event.head_commit.message, 'chore: bump version')"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump Version and Tag
        run: |
          # npm version patch vai alterar o package.json, commitar e criar a tag vX.Y.Z
          npm version patch -m "chore: bump version to %s [skip ci]"
          
          # Empurra o commit do package.json e a nova tag para a master
          git push origin master --follow-tags
